apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: warehouse-org
      defaultBucket: warehouse_sensors
    secureJsonData:
      token: admin-token-12345
