apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: warehouse-system
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME_MIN_32_CHARS_JWT_SIGNING_KEY"
  JWT_REFRESH_SECRET: "CHANGE_ME_MIN_32_CHARS_JWT_REFRESH_KEY"
  INFLUX_TOKEN: "CHANGE_ME_ADMIN_TOKEN_FOR_INFLUX"
  REDIS_PASSWORD: ""
  AWS_SNS_TOPIC_ARN: "CHANGE_ME"
