persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
allow_anonymous true

# MQTT Standard Protocol Port
listener 1883

# MQTT over WebSockets Port
listener 9001
protocol websockets
