apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-frontend
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
    app: frontend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "warehouse-iot.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "warehouse-iot.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_SVC_NAME
              value: {{ include "warehouse-iot.fullname" . }}-backend
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
