apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-secret
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.jwt.refreshSecret | quote }}
  INFLUX_TOKEN: {{ .Values.influx.token | quote }}
  DOCKER_INFLUXDB_INIT_PASSWORD: {{ .Values.db.password | quote }}
  DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: {{ .Values.influx.token | quote }}
  REDIS_PASSWORD: ""
  AWS_SNS_TOPIC_ARN: {{ .Values.aws.snsTopicArn | quote }}
