apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-backend
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-frontend
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-influxdb
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8086
      targetPort: 8086
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-redis
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-mosquitto
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: websockets
      port: 9001
      targetPort: 9001
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: mosquitto
{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "warehouse-iot.fullname" . }}-mysql
  labels:
    {{- include "warehouse-iot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    {{- include "warehouse-iot.selectorLabels" . | nindent 4 }}
    app: mysql
{{- end }}
