db:
  host: warehouse-iot-prod-mysql.cr8o0as8uj0s.ap-south-1.rds.amazonaws.com
  name: warehouse_iot
  port: 3306
  user: root
  password: password

replicaCount: 1

ingress:
  host: warehouse.example.com

autoscaling:
  enabled: false

simulateDevices: "true"

resources:
  backend:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 500m
      memory: 256Mi
  frontend:
    requests:
      cpu: 10m
      memory: 5Mi
    limits:
      cpu: 200m
      memory: 128Mi

redis:
  host: warehouse-iot-prod-redis.wxqtam.0001.aps1.cache.amazonaws.com
  port: 6379

influx:
  url: http://warehouse-iot-production-influxdb:8086
  org: warehouse-org
  bucket: warehouse_sensors
  token: warehouse-iot-influx-token-prod
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 500m
      memory: 512Mi

jwt:
  secret: warehouse-iot-jwt-secret-prod-32chars
  refreshSecret: warehouse-iot-refresh-secret-prod-32c

aws:
  region: ap-south-1
  iotEndpoint: IOT_ENDPOINT_PLACEHOLDER
  sqsQueueUrl: SQS_URL_PLACEHOLDER
  s3Bucket: warehouse-iot-prod-reports
  snsTopicArn: SNS_TOPIC_ARN_PLACEHOLDER

service:
  frontend:
    type: LoadBalancer
  grafana:
    type: LoadBalancer

image:
  backend:
    repository: 446483465469.dkr.ecr.ap-south-1.amazonaws.com/warehouse-iot-prod-backend
    tag: 9af0b3a6bb1f79ff9af7b482819a8add63d061e8
  frontend:
    repository: 446483465469.dkr.ecr.ap-south-1.amazonaws.com/warehouse-iot-prod-frontend
    tag: 9af0b3a6bb1f79ff9af7b482819a8add63d061e8
