replicaCount: 1

ingress:
  host: warehouse.example.com

autoscaling:
  enabled: false

resources:
  backend:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 500m
      memory: 256Mi

redis:
  host: warehouse-iot-production-redis
  frontend:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      cpu: 200m
      memory: 128Mi

influx:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi
